source 'http://rubygems.org'

ruby '2.6.5'
gem 'capybara'
gem 'rspec'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.6'
gem 'celerity'
gem 'capybara-celerity'
gem 'cucumber-core'
gem 'cucumber'
gem 'test-unit'
gem 'rake'
gem 'rack'
gem 'nokogiri', :platforms => [:ruby, :x64_mingw]
gem 'capybara-screenshot'
gem 'parallel_tests'
gem 'syntax'
gem 'rufus-scheduler'
gem 'teamcity_formatter'
gem 'public_suffix'
gem 'rack-test'
gem 'rest-client', :platforms => [:ruby, :x64_mingw]
gem 'json'
gem 'neatjson'
gem 'bson_ext'
gem 'activesupport'
gem 'assert-url'